In [ ]:
# Let matrix M be the matrix we want to decompose

In [1]:
from numpy import array
from numpy import asarray
from numpy import zeros
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Embedding

Using TensorFlow backend.


In [2]:
# define documents
docs = ['Well done!',
		'Good work',
		'Great effort',
		'nice work',
		'Excellent!',
		'Weak',
		'Poor effort!',
		'not good',
		'poor work',
		'Could have done better.']
# define class labels
labels = array([1,1,1,1,1,0,0,0,0,0])

In [3]:
# prepare tokenizer
t = Tokenizer()
t.fit_on_texts(docs)
vocab_size = len(t.word_index) + 1
# integer encode the documents
encoded_docs = t.texts_to_sequences(docs)
print(encoded_docs)
# pad documents to a max length of 4 words

[[6, 2], [3, 1], [7, 4], [8, 1], [9], [10], [5, 4], [11, 3], [5, 1], [12, 13, 2, 14]]


In [4]:
type(encoded_docs)

list

In [5]:
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)

[[ 6  2  0  0]
 [ 3  1  0  0]
 [ 7  4  0  0]
 [ 8  1  0  0]
 [ 9  0  0  0]
 [10  0  0  0]
 [ 5  4  0  0]
 [11  3  0  0]
 [ 5  1  0  0]
 [12 13  2 14]]


In [6]:
# load the whole embedding into memory
embeddings_index = dict()
f = open('../glove_data/glove.6B/glove.6B.100d.txt')
for line in f:
	values = line.split()
	word = values[0]
	coefs = asarray(values[1:], dtype='float32')
	embeddings_index[word] = coefs
f.close()
print('Loaded %s word vectors.' % len(embeddings_index))

FileNotFoundError: [Errno 2] No such file or directory: '../glove_data/glove.6B/glove.6B.100d.txt'

In [ ]:
# create a weight matrix for words in training docs
embedding_matrix = zeros((vocab_size, 100))
for word, i in t.word_index.items():
	embedding_vector = embeddings_index.get(word)
	if embedding_vector is not None:
		embedding_matrix[i] = embedding_vector

In [ ]:
# define model
model = Sequential()
e = Embedding(vocab_size, 100, weights=[embedding_matrix], input_length=4, trainable=False)
model.add(e)
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
# summarize the model
print(model.summary())
# fit the model
model.fit(padded_docs, labels, epochs=50, verbose=0)
# evaluate the model
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('Accuracy: %f' % (accuracy*100))

In [21]:
model = Sequential()
embedding = Embedding( vocab_size, 100, input_length=1  )
model.add(embedding)
model.add(Flatten())
model.add(Dense(5,activation='sigmoid'))

In [16]:
train_x = array(  [  [1] , [2],[3],[4] ] )

In [17]:
train_y = array( [    [0,0,0,1,0], [0,0,1,0,0], [0,1,0,0,0], [0,0,0,0,1]   ]  )

In [18]:
vocab_size = 5

In [24]:
model.predict([1])

array([[0.39590773, 0.37309825, 0.39334664, 0.55541867, 0.3881981 ]],
      dtype=float32)

In [30]:
embedding.weights[0][0]

<tf.Tensor: shape=(100,), dtype=float32, numpy=
array([ 3.57007124e-02, -2.32096445e-02, -4.90398295e-02,  1.47134699e-02,
       -6.58601522e-03, -6.82646036e-03, -4.07556891e-02,  1.10339895e-02,
        4.64746691e-02,  3.33900340e-02,  2.55318545e-02,  1.15167275e-02,
        3.41591127e-02, -2.42596269e-02, -4.00106423e-02, -3.22442651e-02,
        2.57013775e-02, -4.84557748e-02, -2.69672405e-02,  2.56438293e-02,
       -9.01168585e-03, -2.10463405e-02,  3.97637598e-02, -4.70981859e-02,
        2.36223452e-02,  1.88614242e-02, -5.59785217e-03,  4.35889699e-02,
       -3.63927707e-02, -9.49269533e-03, -4.98044491e-02,  2.56957524e-02,
        1.58254616e-02,  1.21947639e-02, -3.31111923e-02, -3.36569548e-02,
       -4.50991169e-02,  3.51453908e-02,  1.69365890e-02, -8.74400139e-05,
       -1.48037672e-02,  3.88452150e-02, -1.19431131e-02,  2.39114836e-03,
       -3.40183601e-02, -4.57908176e-02, -3.72370705e-02, -2.96023618e-02,
       -4.81208675e-02, -2.01481711e-02,  3.05191316

In [23]:
model.compile(optimizer='adam',loss='binary_crossentropy')
model.fit(train_x,train_y,epochs=50,verbose=1)

C:\Users\14087\Anaconda3\lib\site-packages\tensorflow_core\python\framework\indexed_slices.py:433: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


Epoch 1/50
4/4 [==============================] - 1s 132ms/step - loss: 0.6789
Epoch 2/50
4/4 [==============================] - 0s 0us/step - loss: 0.6755
Epoch 3/50
4/4 [==============================] - 0s 259us/step - loss: 0.6721
Epoch 4/50
4/4 [==============================] - 0s 643us/step - loss: 0.6687
Epoch 5/50
4/4 [==============================] - 0s 260us/step - loss: 0.6653
Epoch 6/50
4/4 [==============================] - 0s 500us/step - loss: 0.6619
Epoch 7/50
4/4 [==============================] - 0s 499us/step - loss: 0.6585
Epoch 8/50
4/4 [==============================] - 0s 632us/step - loss: 0.6551
Epoch 9/50
4/4 [==============================] - 0s 251us/step - loss: 0.6517
Epoch 10/50
4/4 [==============================] - 0s 806us/step - loss: 0.6483
Epoch 11/50
4/4 [==============================] - 0s 757us/step - loss: 0.6449
Epoch 12/50
4/4 [==============================] - 0s 822us/step - loss: 0.6415
Epoch 13/50
4/4 [==============================] - 